
<div class="usefull-links">
  <div class="main-title">
    <div class="main-title__container">
      <h1 class="main-title__title">Полезные ссылки</h1>
    </div>
  </div>
  <div class="usefull-links__container"><a class="usefull-link" href="/"><img class="usefull-link__icon" src="/local/templates/surgut/icons/arrow-right_icon.svg" alt="Иконка"/><span class="usefull-link__title">Оплата ЖКХ услуг  </span></a><a class="usefull-link" href="/"><img class="usefull-link__icon" src="/local/templates/surgut/icons/arrow-right_icon.svg" alt="Иконка"/><span class="usefull-link__title">Виртуальная приемная </span></a><a class="usefull-link" href="/"><img class="usefull-link__icon" src="/local/templates/surgut/icons/arrow-right_icon.svg" alt="Иконка"/><span class="usefull-link__title">Пособия и налоги </span></a><a class="usefull-link" href="/"><img class="usefull-link__icon" src="/local/templates/surgut/icons/arrow-right_icon.svg" alt="Иконка"/><span class="usefull-link__title">Расписание общественного транспорта </span></a><a class="usefull-link" href="/"><img class="usefull-link__icon" src="/local/templates/surgut/icons/arrow-right_icon.svg" alt="Иконка"/><span class="usefull-link__title">Выплаты пенсионерам </span></a><a class="usefull-link" href="/"><img class="usefull-link__icon" src="/local/templates/surgut/icons/arrow-right_icon.svg" alt="Иконка"/><span class="usefull-link__title">Запись на публичные слушания </span></a><a class="usefull-link" href="/"><img class="usefull-link__icon" src="/local/templates/surgut/icons/arrow-right_icon.svg" alt="Иконка"/><span class="usefull-link__title">Социальные услуги </span></a><a class="usefull-link" href="/"><img class="usefull-link__icon" src="/local/templates/surgut/icons/arrow-right_icon.svg" alt="Иконка"/><span class="usefull-link__title">Работа в России </span></a>
  </div>
</div>